Tradingpost
Maselkov/Maselkov-Cogs pull request #22
Opened 2017-03-23 19:44 UTC by n1tr0-5urf3r

Added trading post commands for transactions 
invoke with !tp current buys/sells

Returns up to 20 current listings with quantity, your price and maximum price offer at the moment

2017-03-23 22:15 UTC, Maselkov commented
You're doing good work. Will review it tomorrow.

2017-03-24 07:01 UTC, n1tr0-5urf3r commented
Thanks! It is my first python project ever

2017-03-24 11:56 UTC, Maselkov requested changes
It's good but It's making unnecessary API calls - 
* The items endpoint can be requested with ids= parameter, to get multiple items at once (each id separated by comma, see https://wiki.guildwars2.com/wiki/API:2/items)
* Same thing with commerce/listings, you can use ids=

2017-03-24 11:56 UTC, Maselkov commented on guildwars2/guildwars2.py
> +        state = state.lower
Needs brackets after lower
```
state = state.lower()
```

2017-03-24 12:11 UTC, n1tr0-5urf3r commented on guildwars2/guildwars2.py
> +        state = state.lower
I'll look into that

2017-03-24 12:34 UTC, n1tr0-5urf3r commented
Seems to work, API is only called once now for listings and items

2017-03-24 13:12 UTC, merged